language: cpp

before_install:
  - sudo apt-get update -y

script: 
  - cd AntennaTracker && make sitl

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e5e0b55e353e53945b4b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
